### PR TITLE
Fix Notice: Array to string conversion

### PR DESCRIPTION
**Pull request by 5baddi**
Fix  Array to string conversion notice on  src/Pinterest/Transport/Request.php

### CODE REVIEW

**Comment by dirkgroenen** [comment]
Thanks for your PR. 
Unfortunately your PR contains a lot of composer and namespace changes which aren't related to the fix. Please update this so your PR only contains the fix.

**Comment by 5baddi** [comment]
Unnecessary changes have been removed.
Thank you 🙏🏼

**Review by jeandonaldroselin — APPROVED** [review]
It is ready for merge

**Comment by dirkgroenen** [comment]
Merged and released as `0.2.14`, thanks!

**Pull request merged**
